# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'twitter_clone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for twitter_clone
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'twitter_clone-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'twitter_cloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
